# railway.toml

# Lemmy Service
[services.lemmy]
path = "lemmy"
env = {
  LEMMY_ADMIN_PASSWORD = "${LEMMY_ADMIN_PASSWORD}",
  LEMMY_HOSTNAME = "{{ services.lemmy-ui.public_url }}",
  PICTRS_URL = "{{ services.pictrs.public_url }}",
  PICTRS_API_KEY = "${PICTRS_API_KEY}",
}

# Lemmy UI Service
[services.lemmy-ui]
path = "lemmy-ui"
env = {
  LEMMY_UI_LEMMY_EXTERNAL_HOST = "{{ services.lemmy.public_url }}",
  LEMMY_UI_HTTPS = "false",
  LEMMY_UI_DEBUG = "true",
}

# Pictrs Service
[services.pictrs]
path = "pictrs"
env = {
  PICTRS_API_KEY = "${PICTRS_API_KEY}",
}
[services.pictrs.volumes]
"/mnt" = "pictrs-data"

# Proxy Service
[services.proxy]
path = "proxy"
env = {
  LEMMY_HOSTNAME = "{{ services.proxy.public_url }}"
}

# PostgreSQL Plugin
[plugins.postgresql]
